Document: robotkernel-module-posix-timer
Title: Debian robotkernel-module-posix-timer Manual
Author: <insert document author here>
Abstract: This manual describes what robotkernel-module-posix-timer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/robotkernel-module-posix-timer/robotkernel-module-posix-timer.sgml.gz

Format: postscript
Files: /usr/share/doc/robotkernel-module-posix-timer/robotkernel-module-posix-timer.ps.gz

Format: text
Files: /usr/share/doc/robotkernel-module-posix-timer/robotkernel-module-posix-timer.text.gz

Format: HTML
Index: /usr/share/doc/robotkernel-module-posix-timer/html/index.html
Files: /usr/share/doc/robotkernel-module-posix-timer/html/*.html
